### ISSUE TITLE
Snap [Feature Request]

### ISSUE THREAD

**Issue by mikeroyal** [microsoft/Orb#8]
I was wondering if you might have an interest in a [snap](https://snapcraft.io/) version. I would help make the snap and submit a PR if there's any interest now or in the future.
[Crafting your first Electron snap](https://snapcraft.io/#electron)

**Comment by songxueyuan** [comment]
Hey @mikeroyal, thanks for your request, we have dependencies on .NET framework. Is snap store just for linux platform?

**Comment by mikeroyal** [comment]
hi @songxueyuan,

Snaps are mainly for Linux but the engineering team has worked on support for MacOS and soon Windows 10 under WSL 2. 
![Screenshot from 2019-09-14 22-33-28](https://user-images.githubusercontent.com/45159366/64917012-e5cf7280-d73f-11e9-812f-d6b80152a03c.png)

There's also a supported plugin for .NET  https://snapcraft.io/docs/dotnet-plugin

**Comment by songxueyuan** [comment]
@mikeroyal pls let us know when windows support available, and then we can consider publish Orb there.
